### ISSUE TITLE
Xresources for dunst

### ISSUE THREAD

**Issue by bakkeby** [FT-Labs/phyOS-dunst#2]
You do not have the discussions section enabled for this repository so raising an issue instead.

Are you planning on keeping your build up-to-date with upstream dunst going forward?

I found the way colours are handled in dunst is annoying and reading over the issues threads for that project I got the impression that the maintainers are not interested in adding Xresources support and favours regenerating configuration using pywal specifically and stopping and starting the service.

So I added Xresources support for my own use and was thinking that perhaps you might want it as well:
https://pastebin.com/mZZP7zCF

**Comment by FT-Labs** [comment]
Yes, I am trying to update it when I have empty time. 
Also thanks for sharing this, I will apply this patch when I merge it with the next release.

Thanks again!

**Comment by FT-Labs** [comment]
Thanks for this Bakkeby, I've merged it to repo and upstreamed code to original dunst.
